export const unitsCopy = {
  pages: {
    units: {
      title: "Unidades",
      subtitle: "Consulte as unidades sincronizadas do ERP.",
      searchPlaceholder: "Buscar unidades...",
      tableAriaLabel: "Lista de unidades",
    },
    unitUsers: {
      fallbackTitle: "Unidade não encontrada",
      fallbackDescription: "A unidade solicitada não existe ou ainda não foi sincronizada.",
      searchPlaceholder: "Buscar funcionários...",
      tableAriaLabel: "Lista de funcionários da unidade",
    },
  },
  actions: {
    backToUnits: "Voltar",
    details: "Detalhes",
    refresh: "Atualizar dados",
    users: "Funcionários",
  },
  filters: {
    brands: "Bandeiras",
    cities: "Cidades",
    roles: "Perfis",
    status: "Status",
  },
  table: {
    brand: "Bandeira",
    cityState: "Cidade/UF",
    cnpj: "CNPJ",
    companyCode: "Código",
    coordinates: "Coordenadas",
    cpf: "CPF",
    email: "E-mail",
    erpSystem: "Sistema de gestão",
    erpSystemLabel: "ERP Monte Carlo",
    lastAccess: "Último acesso",
    legalName: "Razão social",
    managers: "Gerentes",
    name: "Nome",
    networkIp: "IP da rede",
    noEmail: "Sem e-mail",
    operators: "Operadores",
    passkey: "Passkey",
    phone: "Telefone",
    profile: "Perfil",
    spots: "Vagas",
    state: "UF",
    status: "Status",
    tradeName: "Unidade",
    users: "Funcionários",
    yard: "Pátio",
  },
  details: {
    active: "Ativo",
    inactive: "Inativo",
    notConfigured: "Não configurado",
    noMap: "Coordenadas indisponíveis",
    emptyValue: "—",
    unitTitle: "Detalhes da unidade",
    unitDescription: "Consulte os dados cadastrais, operacionais e de pátio da unidade.",
    userTitle: "Detalhes do funcionário",
    userDescription: "Consulte os dados de acesso e vínculo do funcionário selecionado.",
  },
  yard: {
    statusActive: "Ativo",
    statusInactive: "Inativo",
    statusNotConfigured: "Não configurado",
  },
  empty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "As unidades ainda não foram sincronizadas do ERP.",
    unitUsersTitle: "Nenhum funcionário vinculado",
    unitUsersDescription: "Esta unidade ainda não possui funcionários operacionais vinculados.",
  },
  filteredEmpty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "Ajuste a busca ou os filtros para localizar uma unidade.",
    unitUsersTitle: "Nenhum funcionário encontrado",
    unitUsersDescription: "Ajuste a busca ou os filtros para localizar funcionários desta unidade.",
  },
  errors: {
    unitsLoad: "Não foi possível carregar as unidades.",
    unitsUnavailable: "O serviço de unidades não está configurado.",
    invalidUnitsResponse: "A resposta de unidades retornou em formato inválido.",
    queryLimitExceeded: "A consulta excedeu o limite seguro de registros.",
    unitUsersLoad: "Não foi possível carregar os funcionários da unidade.",
    unitYardLoad: "Não foi possível carregar as configurações de pátio.",
    invalidUnitYardResponse: "A resposta de configurações de pátio retornou em formato inválido.",
  },
} as const
