export const unitsCopy = {
  pages: {
    units: {
      title: "Unidades",
      subtitle: "Consulte as unidades sincronizadas do ERP.",
      searchPlaceholder: "Buscar unidades...",
    },
    unitUsers: {
      fallbackTitle: "Unidade não encontrada",
      fallbackDescription: "A unidade solicitada não existe ou ainda não foi sincronizada.",
      searchPlaceholder: "Buscar funcionários...",
    },
  },
  actions: {
    backToUnits: "Voltar",
    configureYard: "Configurar pátio",
    details: "Detalhes",
    history: "Histórico",
    save: "Salvar",
    saving: "Salvando...",
    cancel: "Cancelar",
    sync: "Sincronizar",
    users: "Funcionários",
  },
  sync: {
    historyLoadError: "Não foi possível carregar o histórico de sincronização.",
    runningTitle: "Sincronização em andamento",
    runningDescription: "A tela será liberada automaticamente ao finalizar.",
    retryLabel: "Recarregar histórico",
    history: {
      title: "Histórico de sincronização",
      description: "Acompanhe as últimas execuções de sincronização de unidades.",
      emptyTitle: "Ainda não há execuções registradas",
      emptyDescription: "Nenhuma execução de sincronização foi registrada até o momento.",
      loadErrorTitle: "Histórico indisponível",
      details: {
        duration: "Duração",
        start: "Início",
        end: "Fim",
        mode: "Modo",
        trigger: "Acionamento",
      },
      modes: {
        full: "Completa",
        incremental: "Incremental",
      },
      statuses: {
        failed: "Falha",
        success: "Sucesso",
        warning: "Atenção",
      },
      triggers: {
        automatic: "Automático",
        manual: "Manual",
      },
      counters: {
        created: "Unidades novas",
        failed: "Unidades com falha",
        received: "Unidades recebidas do ERP",
        unchanged: "Unidades sem alteração",
        updated: "Unidades atualizadas",
      },
    },
    feedback: {
      success: "Sincronização concluída.",
      error: "Não foi possível sincronizar as unidades.",
      inProgress: "Já existe uma sincronização de unidades em andamento.",
      connectionError: "Não foi possível conectar ao serviço de sincronização. Verifique sua conexão e tente novamente.",
    },
  },
  filters: {
    brands: "Bandeiras",
    cities: "Cidades",
    roles: "Perfis",
    states: "Estados",
    status: "Status",
  },
  table: {
    brand: "Bandeira",
    cityState: "Cidade/UF",
    cnpj: "CNPJ",
    companyCode: "Código",
    coordinates: "Coordenadas",
    cpf: "CPF",
    email: "E-mail",
    erpSystem: "Sistema de gestão",
    erpSystemLabel: "ERP Monte Carlo",
    lastAccess: "Último acesso",
    legalName: "Razão social",
    managers: "Gerentes",
    name: "Nome",
    networkIp: "IP da rede",
    noAccess: "Sem acesso",
    noEmail: "Sem e-mail",
    operators: "Operadores",
    passkey: "Passkey",
    phone: "Telefone",
    profile: "Perfil",
    spots: "Vagas",
    state: "UF",
    status: "Status",
    tradeName: "Unidade",
    users: "Funcionários",
    yard: "Pátio",
  },
  details: {
    active: "Ativo",
    inactive: "Inativo",
    noMap: "Coordenadas indisponíveis",
    emptyValue: "—",
  },
  yard: {
    dialogTitle: "Configurar pátio da unidade",
    statusLabel: "Status do pátio",
    spotsLabel: "Quantidade de vagas",
    statusActive: "Ativo",
    statusInactive: "Inativo",
    statusPlaceholder: "Selecione",
    validationInvalidSpots: "Informe uma quantidade de vagas válida.",
    feedback: {
      success: "Configuração de pátio atualizada.",
      error: "Não foi possível salvar a configuração de pátio.",
    },
  },
  empty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "As unidades ainda não foram sincronizadas do ERP.",
    unitUsersTitle: "Nenhum funcionário vinculado",
    unitUsersDescription: "Esta unidade ainda não possui funcionários operacionais vinculados.",
  },
  filteredEmpty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "Ajuste a busca ou os filtros para localizar uma unidade.",
    unitUsersTitle: "Nenhum funcionário encontrado",
    unitUsersDescription: "Ajuste a busca ou os filtros para localizar funcionários desta unidade.",
  },
  errors: {
    unitsLoad: "Não foi possível carregar as unidades.",
    unitsUnavailable: "O serviço de unidades não está configurado.",
    unitUsersLoad: "Não foi possível carregar os funcionários da unidade.",
    unitYardLoad: "Não foi possível carregar as configurações de pátio.",
    unitYardSave: "Não foi possível salvar a configuração de pátio.",
    unitYardInvalidUnit: "Unidade inválida para configuração de pátio.",
  },
} as const
