export const clientsCopy = {
  pages: {
    clients: {
      title: "Clientes",
      subtitle: "Consulte clientes ativos sincronizados do ERP.",
      searchPlaceholder: "Buscar por código, nome, fantasia, documento, cidade ou veículos...",
      accessDeniedTitle: "Acesso restrito a clientes",
      accessDeniedDescription: "Seu perfil não possui permissão para consultar clientes sincronizados.",
    },
    clientVehicles: {
      fallbackTitle: "Cliente não encontrado",
      fallbackDescription: "O cliente solicitado não existe ou ainda não foi sincronizado.",
      invalidTitle: "Código de cliente inválido",
      invalidDescription: "Verifique o endereço acessado e tente novamente.",
      loadingTitle: "Carregando cliente",
      loadingDescription: "Aguarde enquanto os veículos vinculados são consultados.",
      accessDeniedTitle: "Acesso restrito a veículos",
      accessDeniedDescription: "Seu perfil não possui permissão para consultar veículos de clientes.",
      searchPlaceholder: "Buscar por código, cliente, documento, placa, veículo ou motorista...",
    },
  },
  actions: {
    backToClients: "Voltar",
    details: "Detalhes",
    history: "Histórico",
    openVehicles: "Veículos",
    retry: "Tentar novamente",
    sync: "Sincronizar",
    toggleClientVip: "Cliente VIP",
    toggleVehicleVip: "Veículo VIP",
    updating: "Atualizando...",
  },
  accessibility: {
    clientVip: "Cliente VIP",
    vehicleVip: "Veículo VIP",
  },
  sync: {
    historyLoadError: "Não foi possível carregar o histórico de sincronização.",
    runningTitle: "Sincronização em andamento",
    runningDescription: "A tela será liberada automaticamente ao finalizar.",
    retryLabel: "Recarregar histórico",
    history: {
      title: "Histórico de sincronização",
      description: "Acompanhe as últimas execuções de sincronização de clientes e veículos.",
      emptyTitle: "Ainda não há execuções registradas",
      emptyDescription: "Nenhuma execução de sincronização foi registrada até o momento.",
      loadErrorTitle: "Histórico indisponível",
      details: {
        duration: "Duração",
        start: "Início",
        end: "Fim",
        mode: "Modo",
        trigger: "Acionamento",
      },
      modes: {
        full: "Completa",
        incremental: "Incremental",
      },
      statuses: {
        failed: "Falha",
        success: "Sucesso",
        warning: "Atenção",
      },
      triggers: {
        automatic: "Automático",
        manual: "Manual",
      },
      counters: {
        clientsCreated: "Clientes novos",
        clientsFailed: "Clientes com falha",
        clientsReceived: "Clientes recebidos do ERP",
        clientsRejected: "Clientes rejeitados",
        clientsUnchanged: "Clientes sem alteração",
        clientsUpdated: "Clientes atualizados",
        vehiclesCreated: "Veículos novos",
        vehiclesFailed: "Veículos com falha",
        vehiclesReceived: "Veículos recebidos",
        vehiclesRejected: "Veículos rejeitados",
        vehiclesUnchanged: "Veículos sem alteração",
        vehiclesUpdated: "Veículos atualizados",
      },
    },
    feedback: {
      success: "Sincronização concluída.",
      error: "Não foi possível sincronizar os clientes.",
      inProgress: "Já existe uma sincronização de clientes em andamento.",
    },
  },
  filters: {
    plates: "Placas",
    status: "Status",
    vip: "VIP",
  },
  table: {
    active: "Ativo",
    cityState: "Cidade/UF",
    client: "Cliente",
    code: "Código",
    customerCode: "Código do cliente",
    document: "CNPJ/CPF",
    driver: "Motorista",
    email: "E-mail",
    financialBlock: "Bloqueio financeiro",
    inactive: "Inativo",
    invalid: "Inválido",
    lastPurchase: "Data da última compra",
    legalName: "Nome/Razão social",
    no: "Não",
    phone: "Telefone",
    plate: "Placa",
    registrationDate: "Data de cadastro",
    status: "Status",
    tradeName: "Nome fantasia",
    vehicle: "Veículo",
    vehicleCode: "Código do veículo",
    vehicles: "Veículos",
    vip: "VIP",
    yes: "Sim",
  },
  empty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Os clientes ainda não foram sincronizados do ERP.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Este cliente ainda não possui veículos sincronizados.",
  },
  filteredEmpty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Ajuste a busca ou os filtros para localizar um cliente.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Ajuste a busca ou os filtros para localizar um veículo.",
  },
  feedback: {
    clientVip: {
      success: "Status VIP do cliente atualizado.",
      error: "Não foi possível atualizar o status VIP do cliente.",
    },
    vehicleVip: {
      success: "Status VIP do veículo atualizado.",
      error: "Não foi possível atualizar o status VIP do veículo.",
    },
  },
  errors: {
    clientIdInvalid: "O código do cliente informado é inválido.",
    clientsLoad: "Não foi possível carregar os clientes.",
    clientsUnavailable: "O serviço de clientes não está configurado.",
    invalidClientsResponse: "A resposta de clientes retornou em formato inválido.",
    invalidSyncHistoryResponse: "A resposta do histórico de sincronização é inválida.",
    invalidVehiclesResponse: "A resposta de veículos retornou em formato inválido.",
    vipRulesLoad: "Não foi possível carregar as regras VIP de clientes.",
    vipRulesUnavailable: "O serviço de regras VIP de clientes não está configurado.",
    syncLimitExceeded: "A busca de clientes excedeu o limite seguro de páginas.",
    syncUnavailable: "Não foi possível conectar ao serviço de sincronização. Verifique sua conexão e tente novamente.",
    vehiclesLoad: "Não foi possível carregar os veículos do cliente.",
  },
  shared: {
    emptyValue: "—",
    notFinished: "Em andamento",
  },
} as const
