export const clientsCopy = {
  pages: {
    clients: {
      title: "Clientes",
      subtitle: "Consulte clientes ativos sincronizados do ERP.",
      searchPlaceholder: "Buscar por código, nome, fantasia, documento, cidade ou veículos...",
    },
    clientVehicles: {
      fallbackTitle: "Cliente não encontrado",
      fallbackDescription: "O cliente solicitado não existe ou ainda não foi sincronizado.",
      searchPlaceholder: "Buscar por código, cliente, documento, placa, veículo ou motorista...",
    },
  },
  actions: {
    backToClients: "Voltar",
    details: "Detalhes",
    history: "Histórico",
    openVehicles: "Veículos",
    sync: "Sincronizar",
    toggleClientVip: "Cliente VIP",
    toggleVehicleVip: "Veículo VIP",
  },
  accessibility: {
    clientVip: "Cliente VIP",
    vehicleVip: "Veículo VIP",
  },
  sync: {
    historyLoadError: "Não foi possível carregar o histórico de sincronização.",
    runningTitle: "Sincronização em andamento",
    runningDescription: "A tela será liberada automaticamente ao finalizar.",
    history: {
      title: "Histórico de sincronização",
      description: "Acompanhe as últimas execuções de sincronização de clientes e veículos.",
      emptyTitle: "Ainda não há execuções registradas",
      emptyDescription: "Nenhuma execução de sincronização foi registrada até o momento.",
      counters: {
        clientsCreated: "Clientes novos",
        clientsFailed: "Clientes com falha",
        clientsReceived: "Clientes recebidos do ERP",
        clientsUnchanged: "Clientes sem alteração",
        clientsUpdated: "Clientes atualizados",
        vehiclesCreated: "Veículos novos",
        vehiclesFailed: "Veículos com falha",
        vehiclesReceived: "Veículos recebidos",
        vehiclesUnchanged: "Veículos sem alteração",
        vehiclesUpdated: "Veículos atualizados",
      },
    },
    feedback: {
      success: "Sincronização concluída.",
      error: "Não foi possível sincronizar os clientes.",
      inProgress: "Já existe uma sincronização de clientes em andamento.",
    },
  },
  filters: {
    plates: "Placas",
    status: "Status",
    vip: "VIP",
  },
  table: {
    active: "Ativo",
    cityState: "Cidade/UF",
    client: "Cliente",
    code: "Código",
    customerCode: "Código do cliente",
    document: "CNPJ/CPF",
    driver: "Motorista",
    email: "E-mail",
    financialBlock: "Bloqueio financeiro",
    inactive: "Inativo",
    lastPurchase: "Data da última compra",
    legalName: "Nome/Razão social",
    no: "Não",
    phone: "Telefone",
    plate: "Placa",
    registrationDate: "Data de cadastro",
    status: "Status",
    tradeName: "Nome fantasia",
    vehicle: "Veículo",
    vehicleCode: "Código do veículo",
    vehicles: "Veículos",
    vip: "VIP",
    yes: "Sim",
  },
  empty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Os clientes ainda não foram sincronizados do ERP.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Este cliente ainda não possui veículos sincronizados.",
  },
  filteredEmpty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Ajuste a busca ou os filtros para localizar um cliente.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Ajuste a busca ou os filtros para localizar um veículo.",
  },
  feedback: {
    clientVip: {
      loading: "Atualizando status VIP do cliente...",
      success: "Status VIP do cliente atualizado.",
      error: "Não foi possível atualizar o status VIP do cliente.",
    },
    vehicleVip: {
      loading: "Atualizando status VIP do veículo...",
      success: "Status VIP do veículo atualizado.",
      error: "Não foi possível atualizar o status VIP do veículo.",
    },
  },
  errors: {
    clientIdInvalid: "O código do cliente informado é inválido.",
    clientsLoad: "Não foi possível carregar os clientes.",
    invalidClientsResponse: "A resposta de clientes retornou em formato inválido.",
    invalidSyncHistoryResponse: "A resposta do histórico de sincronização é inválida.",
    syncLimitExceeded: "A busca de clientes excedeu o limite seguro de páginas.",
    syncUnavailable: "Não foi possível conectar ao serviço de sincronização. Verifique sua conexão e tente novamente.",
    vehiclesLoad: "Não foi possível carregar os veículos do cliente.",
  },
  shared: {
    emptyValue: "—",
  },
} as const
