export const clientsCopy = {
  pages: {
    clients: {
      title: "Clientes",
      subtitle: "Consulte os clientes ativos sincronizados do ERP.",
      searchPlaceholder: "Buscar clientes...",
      tableAriaLabel: "Lista de clientes",
    },
    clientVehicles: {
      fallbackTitle: "Cliente não encontrado",
      fallbackDescription: "O cliente solicitado não existe ou ainda não foi sincronizado.",
      invalidTitle: "Código de cliente inválido",
      invalidDescription: "Verifique o endereço acessado e tente novamente.",
      searchPlaceholder: "Buscar veículos...",
      tableAriaLabel: "Lista de veículos do cliente",
    },
  },
  actions: {
    backToClients: "Voltar",
    details: "Detalhes",
    openVehicles: "Exibir veículos",
    refresh: "Atualizar dados",
  },
  filters: {
    cities: "Cidades",
    plates: "Placas",
    status: "Status",
  },
  table: {
    active: "Ativo",
    cityState: "Cidade/UF",
    client: "Cliente",
    code: "Código",
    customerCode: "Código do cliente",
    document: "CNPJ/CPF",
    driver: "Motorista",
    email: "E-mail",
    financialBlock: "Bloqueio financeiro",
    inactive: "Inativo",
    lastPurchase: "Data da última compra",
    legalName: "Nome/Razão social",
    no: "Não",
    phone: "Telefone",
    plate: "Placa",
    registrationDate: "Data de cadastro",
    status: "Status",
    tradeName: "Nome fantasia",
    vehicle: "Veículo",
    vehicleCode: "Código do veículo",
    vehicles: "Veículos",
    yes: "Sim",
  },
  empty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Os clientes ainda não foram sincronizados do ERP.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Este cliente ainda não possui veículos sincronizados.",
  },
  filteredEmpty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Ajuste a busca ou os filtros para localizar um cliente.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Ajuste a busca ou os filtros para localizar um veículo.",
  },
  details: {
    clientTitle: "Detalhes do cliente",
    clientDescription: "Consulte os dados cadastrais e comerciais do cliente selecionado.",
    vehicleTitle: "Detalhes do veículo",
    vehicleDescription: "Consulte os dados do veículo vinculado ao cliente.",
  },
  errors: {
    clientIdInvalid: "O código do cliente informado é inválido.",
    clientsLoad: "Não foi possível carregar os clientes.",
    clientsUnavailable: "O serviço de clientes não está configurado.",
    invalidClientsResponse: "A resposta de clientes retornou em formato inválido.",
    invalidVehiclesResponse: "A resposta de veículos retornou em formato inválido.",
    queryLimitExceeded: "A consulta excedeu o limite seguro de registros.",
    vehiclesLoad: "Não foi possível carregar os veículos do cliente.",
  },
  shared: {
    emptyValue: "—",
  },
} as const
