export const pricesCopy = {
  page: {
    title: "Preços",
    subtitle: "Gerencie tabelas de preço, vigência, carência, tolerância e faixas comerciais.",
  },
  actions: {
    add: "Adicionar",
    save: "Salvar",
    cancel: "Cancelar",
    details: "Detalhes",
  },
  filters: {
    scope: "Escopo",
    status: "Status",
    unitSearchPlaceholder: "Buscar por unidade...",
    searchPlaceholder: "Buscar tabelas de preço...",
  },
  table: {
    scope: "Escopo",
    unit: "Unidade",
    charge: "Cobrança",
    cycle: "Ciclo",
    grace: "Carência",
    tolerance: "Tolerância",
    startsAt: "Início",
    endsAt: "Fim",
    status: "Status",
    version: "Versão",
    tiers: "Faixas",
    reason: "Justificativa",
    notes: "Observações",
    updatedAt: "Atualizado em",
  },
  labels: {
    network: "Rede",
    unit: "Unidade",
    allUnits: "Todas as unidades",
    active: "Ativa",
    inactive: "Inativa",
    scheduled: "Agendada",
    expired: "Expirada",
    noEndDate: "Sem fim",
    emptyValue: "—",
    noTiers: "Sem faixas adicionais",
  },
  form: {
    title: "Adicionar tabela de preço",
    description: "Cadastre uma tabela comercial real no banco de dados.",
    scope: "Escopo",
    unitId: "Código da unidade",
    unitName: "Nome da unidade",
    amount: "Valor base",
    cycleHours: "Ciclo em horas",
    graceMinutes: "Carência em minutos",
    toleranceMinutes: "Tolerância em minutos",
    startsAt: "Início da vigência",
    endsAt: "Fim da vigência",
    status: "Status",
    reason: "Justificativa",
    notes: "Observações",
    scopePlaceholder: "Selecione o escopo",
    statusPlaceholder: "Selecione o status",
    unitPlaceholder: "Selecione a unidade",
    unitEmpty: "Nenhuma unidade encontrada.",
    validation: {
      unitId: "Informe o código da unidade.",
      unitName: "Informe o nome da unidade.",
      amount: "Informe um valor base válido.",
      cycleHours: "Informe um ciclo entre 1 e 720 horas.",
      graceMinutes: "Informe uma carência entre 0 e 1440 minutos.",
      toleranceMinutes: "Informe uma tolerância entre 0 e 240 minutos.",
      startsAt: "Informe o início da vigência.",
      endsAt: "Informe uma data final válida e posterior ao início.",
      reason: "Informe uma justificativa com pelo menos 10 caracteres.",
    },
  },
  empty: {
    title: "Nenhuma tabela de preço cadastrada",
    description: "Cadastre uma tabela de preço para iniciar a configuração comercial.",
  },
  filteredEmpty: {
    title: "Nenhuma tabela encontrada",
    description: "Ajuste a busca ou os filtros aplicados.",
  },
  feedback: {
    loadError: "Não foi possível carregar as tabelas de preço.",
    save: {
      loading: "Salvando tabela de preço...",
      success: "Tabela de preço salva.",
      error: "Não foi possível salvar a tabela de preço.",
    },
  },
} as const
