export const toastCopy = {
  messages: {
    "common.success": "Operação concluída.",
    "common.error": "Não foi possível concluir a operação.",
    "common.info": "Informação atualizada.",
    "common.warning": "Atenção necessária.",
    "common.loading": "Processando...",
  },
  translations: {
    success: "Operação concluída.",
    error: "Não foi possível concluir a operação.",
    warning: "Atenção necessária.",
    info: "Informação atualizada.",
    loading: "Processando...",
    "usuário atualizado": "Usuário atualizado com sucesso.",
    "usuário cadastrado": "Usuário cadastrado com sucesso.",
    "senha alterada": "Senha alterada com sucesso.",
    "informações salvas": "Informações salvas com sucesso.",
    "aplicativo adicionado": "Aplicativo adicionado com sucesso.",
    "configuração de pátio atualizada": "Configuração de pátio atualizada com sucesso.",
    "exportação de auditoria gerada": "Exportação de auditoria concluída.",
    "não foi possível alterar a senha": "Não foi possível alterar a senha.",
    "não foi possível salvar as informações": "Não foi possível salvar as informações.",
    "não foi possível adicionar o aplicativo": "Não foi possível adicionar o aplicativo.",
    "não foi possível salvar a configuração de pátio": "Não foi possível salvar a configuração de pátio.",
    "não foi possível atualizar todas as notificações": "Não foi possível atualizar todas as notificações.",
    saved: "Salvo com sucesso.",
    "saved successfully": "Salvo com sucesso.",
    "created successfully": "Criado com sucesso.",
    "updated successfully": "Atualizado com sucesso.",
    "deleted successfully": "Excluído com sucesso.",
    "something went wrong": "Algo deu errado.",
    "network error": "Erro de conexão.",
    unauthorized: "Acesso não autorizado.",
    forbidden: "Você não tem permissão para executar esta ação.",
    "not found": "Registro não encontrado.",
  },
} as const

export type ToastMessageKey = keyof typeof toastCopy.messages
