import { env } from "@/config"
import { type ErpClientPayload, type ErpClientVehiclePayload } from "@/features/clients"
import { type ErpUnitPayload } from "@/features/units"

export function isErpCatalogMockEnabled() {
  return env.erpCatalogMockEnabled
}

export const mockErpUnitsPayload = [
  {
    cod_empresa: 101,
    nom_razao_social: "Rede Monte Carlo Campinas Ltda.",
    nom_fantasia: "Monte Carlo Campinas Centro",
    num_cnpj: "12.345.678/0001-90",
    cod_bandeira: 1,
    des_bandeira: "Monte Carlo",
    cod_cidade: 3509502,
    nom_cidade: "Campinas",
    nom_estado: "São Paulo",
    sgl_estado: "SP",
    des_coordenada_empresa: "-22.905640,-47.060830",
    ip_rede: "10.101.0.10",
    nom_banco_dados: "mc_campinas_centro",
  },
  {
    cod_empresa: 102,
    nom_razao_social: "Rede Monte Carlo Americana Ltda.",
    nom_fantasia: "Monte Carlo Americana",
    num_cnpj: "12.345.678/0002-70",
    cod_bandeira: 1,
    des_bandeira: "Monte Carlo",
    cod_cidade: 3501608,
    nom_cidade: "Americana",
    nom_estado: "São Paulo",
    sgl_estado: "SP",
    des_coordenada_empresa: "-22.737430,-47.333130",
    ip_rede: "10.102.0.10",
    nom_banco_dados: "mc_americana",
  },
  {
    cod_empresa: 201,
    nom_razao_social: "Rede Monte Carlo Belo Horizonte Ltda.",
    nom_fantasia: "Monte Carlo Savassi",
    num_cnpj: "12.345.678/0003-50",
    cod_bandeira: 1,
    des_bandeira: "Monte Carlo",
    cod_cidade: 3106200,
    nom_cidade: "Belo Horizonte",
    nom_estado: "Minas Gerais",
    sgl_estado: "MG",
    des_coordenada_empresa: "-19.939120,-43.933060",
    ip_rede: "10.201.0.10",
    nom_banco_dados: "mc_bh_savassi",
  },
  {
    cod_empresa: 301,
    nom_razao_social: "Rede Monte Carlo Curitiba Ltda.",
    nom_fantasia: "Monte Carlo Batel",
    num_cnpj: "12.345.678/0004-31",
    cod_bandeira: 1,
    des_bandeira: "Monte Carlo",
    cod_cidade: 4106902,
    nom_cidade: "Curitiba",
    nom_estado: "Paraná",
    sgl_estado: "PR",
    des_coordenada_empresa: "-25.441210,-49.283880",
    ip_rede: "10.301.0.10",
    nom_banco_dados: "mc_curitiba_batel",
  },
  {
    cod_empresa: 401,
    nom_razao_social: "Rede Monte Carlo Rio de Janeiro Ltda.",
    nom_fantasia: "Monte Carlo Barra",
    num_cnpj: "12.345.678/0005-12",
    cod_bandeira: 1,
    des_bandeira: "Monte Carlo",
    cod_cidade: 3304557,
    nom_cidade: "Rio de Janeiro",
    nom_estado: "Rio de Janeiro",
    sgl_estado: "RJ",
    des_coordenada_empresa: "-23.000370,-43.365890",
    ip_rede: "10.401.0.10",
    nom_banco_dados: "mc_rio_barra",
  },
] satisfies readonly ErpUnitPayload[]

export const mockErpClientsPayload = [
  {
    cod_pessoa: 1001,
    nom_pessoa: "Transportes Aurora Ltda.",
    nom_fantasia: "Aurora Transportes",
    num_cnpj_cpf: "22.111.333/0001-44",
    des_email_1: "operacao@auroratransportes.example",
    num_telefone_1: "(11) 4000-1001",
    nom_cidade: "Campinas",
    sgl_estado: "SP",
    dta_cadastro: "2024-02-10",
    ind_pessoa_ativa: "S",
    bloqueio_financeiro: "N",
    qtd_veiculos: 3,
    dta_ultima_compra: "2026-07-08",
    is_active_120d: true,
  },
  {
    cod_pessoa: 1002,
    nom_pessoa: "Comercial Serra Azul S.A.",
    nom_fantasia: "Serra Azul",
    num_cnpj_cpf: "18.555.222/0001-03",
    des_email_1: "frota@serraazul.example",
    num_telefone_1: "(19) 4000-1002",
    nom_cidade: "Americana",
    sgl_estado: "SP",
    dta_cadastro: "2023-11-18",
    ind_pessoa_ativa: "S",
    bloqueio_financeiro: "N",
    qtd_veiculos: 2,
    dta_ultima_compra: "2026-07-04",
    is_active_120d: true,
  },
  {
    cod_pessoa: 1003,
    nom_pessoa: "Logística Horizonte Ltda.",
    nom_fantasia: "Horizonte Log",
    num_cnpj_cpf: "31.222.444/0001-88",
    des_email_1: "cadastro@horizontelog.example",
    num_telefone_1: "(31) 4000-1003",
    nom_cidade: "Belo Horizonte",
    sgl_estado: "MG",
    dta_cadastro: "2024-08-21",
    ind_pessoa_ativa: "S",
    bloqueio_financeiro: "N",
    qtd_veiculos: 2,
    dta_ultima_compra: "2026-06-28",
    is_active_120d: true,
  },
  {
    cod_pessoa: 1004,
    nom_pessoa: "Posto Jardim Sul Ltda.",
    nom_fantasia: "Jardim Sul",
    num_cnpj_cpf: "09.777.555/0001-66",
    des_email_1: "financeiro@jardimsul.example",
    num_telefone_1: "(41) 4000-1004",
    nom_cidade: "Curitiba",
    sgl_estado: "PR",
    dta_cadastro: "2025-01-15",
    ind_pessoa_ativa: "S",
    bloqueio_financeiro: "S",
    qtd_veiculos: 1,
    dta_ultima_compra: "2026-07-11",
    is_active_120d: true,
  },
  {
    cod_pessoa: 1005,
    nom_pessoa: "Frota Atlântico Ltda.",
    nom_fantasia: "Frota Atlântico",
    num_cnpj_cpf: "44.888.111/0001-20",
    des_email_1: "gestao@frotaatlantico.example",
    num_telefone_1: "(21) 4000-1005",
    nom_cidade: "Rio de Janeiro",
    sgl_estado: "RJ",
    dta_cadastro: "2024-05-02",
    ind_pessoa_ativa: "S",
    bloqueio_financeiro: "N",
    qtd_veiculos: 4,
    dta_ultima_compra: "2026-07-10",
    is_active_120d: true,
  },
] satisfies readonly ErpClientPayload[]

export const mockErpClientVehiclesPayload = [
  {
    cod_veiculo: 5001,
    cod_pessoa: 1001,
    nom_pessoa: "Transportes Aurora Ltda.",
    nom_fantasia: "Aurora Transportes",
    num_cnpj_cpf: "22.111.333/0001-44",
    num_placa: "FRT1A01",
    des_veiculo: "Mercedes-Benz Sprinter",
    nom_motorista: "Equipe Aurora",
  },
  {
    cod_veiculo: 5002,
    cod_pessoa: 1001,
    nom_pessoa: "Transportes Aurora Ltda.",
    nom_fantasia: "Aurora Transportes",
    num_cnpj_cpf: "22.111.333/0001-44",
    num_placa: "FRT1A02",
    des_veiculo: "Volkswagen Delivery",
    nom_motorista: "Equipe Aurora",
  },
  {
    cod_veiculo: 5003,
    cod_pessoa: 1001,
    nom_pessoa: "Transportes Aurora Ltda.",
    nom_fantasia: "Aurora Transportes",
    num_cnpj_cpf: "22.111.333/0001-44",
    num_placa: "FRT1A03",
    des_veiculo: "Fiat Fiorino",
    nom_motorista: "Equipe Aurora",
  },
  {
    cod_veiculo: 5011,
    cod_pessoa: 1002,
    nom_pessoa: "Comercial Serra Azul S.A.",
    nom_fantasia: "Serra Azul",
    num_cnpj_cpf: "18.555.222/0001-03",
    num_placa: "SAZ2B11",
    des_veiculo: "Chevrolet S10",
    nom_motorista: "Equipe Serra Azul",
  },
  {
    cod_veiculo: 5012,
    cod_pessoa: 1002,
    nom_pessoa: "Comercial Serra Azul S.A.",
    nom_fantasia: "Serra Azul",
    num_cnpj_cpf: "18.555.222/0001-03",
    num_placa: "SAZ2B12",
    des_veiculo: "Toyota Hilux",
    nom_motorista: "Equipe Serra Azul",
  },
  {
    cod_veiculo: 5021,
    cod_pessoa: 1003,
    nom_pessoa: "Logística Horizonte Ltda.",
    nom_fantasia: "Horizonte Log",
    num_cnpj_cpf: "31.222.444/0001-88",
    num_placa: "HZL3C21",
    des_veiculo: "Iveco Daily",
    nom_motorista: "Equipe Horizonte",
  },
  {
    cod_veiculo: 5022,
    cod_pessoa: 1003,
    nom_pessoa: "Logística Horizonte Ltda.",
    nom_fantasia: "Horizonte Log",
    num_cnpj_cpf: "31.222.444/0001-88",
    num_placa: "HZL3C22",
    des_veiculo: "Renault Master",
    nom_motorista: "Equipe Horizonte",
  },
  {
    cod_veiculo: 5031,
    cod_pessoa: 1004,
    nom_pessoa: "Posto Jardim Sul Ltda.",
    nom_fantasia: "Jardim Sul",
    num_cnpj_cpf: "09.777.555/0001-66",
    num_placa: "JDS4D31",
    des_veiculo: "Ford Ranger",
    nom_motorista: "Equipe Jardim Sul",
  },
  {
    cod_veiculo: 5041,
    cod_pessoa: 1005,
    nom_pessoa: "Frota Atlântico Ltda.",
    nom_fantasia: "Frota Atlântico",
    num_cnpj_cpf: "44.888.111/0001-20",
    num_placa: "ATL5E41",
    des_veiculo: "Volkswagen Constellation",
    nom_motorista: "Equipe Atlântico",
  },
  {
    cod_veiculo: 5042,
    cod_pessoa: 1005,
    nom_pessoa: "Frota Atlântico Ltda.",
    nom_fantasia: "Frota Atlântico",
    num_cnpj_cpf: "44.888.111/0001-20",
    num_placa: "ATL5E42",
    des_veiculo: "Mercedes-Benz Atego",
    nom_motorista: "Equipe Atlântico",
  },
  {
    cod_veiculo: 5043,
    cod_pessoa: 1005,
    nom_pessoa: "Frota Atlântico Ltda.",
    nom_fantasia: "Frota Atlântico",
    num_cnpj_cpf: "44.888.111/0001-20",
    num_placa: "ATL5E43",
    des_veiculo: "Volvo VM",
    nom_motorista: "Equipe Atlântico",
  },
  {
    cod_veiculo: 5044,
    cod_pessoa: 1005,
    nom_pessoa: "Frota Atlântico Ltda.",
    nom_fantasia: "Frota Atlântico",
    num_cnpj_cpf: "44.888.111/0001-20",
    num_placa: "ATL5E44",
    des_veiculo: "Scania P320",
    nom_motorista: "Equipe Atlântico",
  },
] satisfies readonly ErpClientVehiclePayload[]
