export const rulesCopy = {
  page: {
    title: "Regras",
    subtitle: "Gerencie regras VIP aplicáveis a clientes e veículos.",
  },
  actions: {
    add: "Adicionar regra",
    details: "Detalhes",
    activate: "Ativar regra",
    deactivate: "Inativar regra",
    save: "Salvar regra",
    cancel: "Cancelar",
  },
  filters: {
    targetType: "Tipo",
    status: "Status",
    searchPlaceholder: "Buscar regras VIP...",
  },
  table: {
    type: "Tipo",
    client: "Cliente",
    clientId: "Código do cliente",
    vehicle: "Veículo",
    vehicleId: "Código do veículo",
    vehiclePlate: "Placa",
    scope: "Abrangência",
    units: "Unidades",
    vehicles: "Veículos",
    status: "Status",
    updatedAt: "Atualizado em",
    reason: "Justificativa",
    notes: "Observações",
  },
  labels: {
    client: "Cliente",
    vehicle: "Veículo",
    active: "Ativa",
    inactive: "Inativa",
    allVehicles: "Todos os veículos",
    allUnits: "Todas as unidades",
    specificVehicle: "Veículo específico",
    specificUnits: "Unidades específicas",
    notConfigured: "Não configurado",
    emptyValue: "—",
  },
  form: {
    title: "Adicionar regra VIP",
    description: "Cadastre uma regra VIP real na tabela comercial.",
    targetType: "Tipo de regra",
    clientId: "Código do cliente",
    clientName: "Nome do cliente",
    vehicleId: "Código do veículo",
    vehiclePlate: "Placa do veículo",
    appliesToAllUnits: "Aplicar em todas as unidades",
    unitIds: "Unidades específicas",
    unitIdsHint: "Informe códigos separados por vírgula quando a regra não valer para todas as unidades.",
    reason: "Justificativa",
    notes: "Observações",
    status: "Status",
    targetPlaceholder: "Selecione o tipo",
    statusPlaceholder: "Selecione o status",
    validation: {
      clientId: "Informe um código de cliente válido.",
      clientName: "Informe o nome do cliente.",
      vehicleId: "Informe um código de veículo válido.",
      vehiclePlate: "Informe a placa do veículo.",
      reason: "Informe uma justificativa com pelo menos 10 caracteres.",
    },
  },
  empty: {
    title: "Nenhuma regra comercial cadastrada",
    description: "Cadastre uma regra VIP para iniciar o controle comercial.",
  },
  filteredEmpty: {
    title: "Nenhuma regra encontrada",
    description: "Ajuste a busca ou os filtros aplicados.",
  },
  feedback: {
    loadError: "Não foi possível carregar as regras VIP.",
    save: {
      loading: "Salvando regra VIP...",
      success: "Regra VIP salva.",
      error: "Não foi possível salvar a regra VIP.",
    },
    toggle: {
      loading: "Atualizando regra VIP...",
      success: "Regra VIP atualizada.",
      error: "Não foi possível atualizar a regra VIP.",
    },
  },
} as const
