export const rulesCopy = {
  page: {
    title: "Regras",
    subtitle: "Gerencie regras comerciais, isenções e alertas operacionais.",
  },
  actions: {
    add: "Adicionar",
    details: "Detalhes",
    activate: "Ativar",
    deactivate: "Inativar",
    save: "Salvar",
    cancel: "Cancelar",
  },
  filters: {
    targetType: "Tipo",
    status: "Status",
    searchPlaceholder: "Buscar regras...",
  },
  table: {
    type: "Tipo",
    client: "Cliente",
    clientId: "Código do cliente",
    vehicle: "Veículo",
    vehicleId: "Código do veículo",
    vehiclePlate: "Placa",
    scope: "Abrangência",
    summary: "Regra",
    units: "Unidades",
    vehicles: "Veículos",
    status: "Status",
    updatedAt: "Atualizado em",
    reason: "Justificativa",
    notes: "Observações",
    fuelMinLiters: "Litros mínimos",
    benefitHours: "Horas de benefício",
    yardOccupancyThreshold: "Limite de ocupação",
    yardStaleVehicleHours: "Tempo sem saída",
  },
  labels: {
    active: "Ativa",
    allUnits: "Todas as unidades",
    allVehicles: "Todos os veículos",
    client: "Cliente",
    emptyValue: "—",
    fuelBenefit: "Abastecimento",
    inactive: "Inativa",
    network: "Global",
    notConfigured: "Não configurado",
    specificUnits: "Unidades específicas",
    specificVehicle: "Veículo específico",
    unit: "Unidade",
    vehicle: "Veículo",
    vip: "Cliente VIP",
    yardCleaning: "Limpeza de pátio",
    yardCleaningOccupancy: "Limpeza por ocupação",
    yardCleaningStaleVehicle: "Limpeza por permanência",
  },
  form: {
    title: "Adicionar regra",
    description: "Cadastre uma regra comercial ou operacional.",
    ruleType: "Tipo de regra",
    applyAllVehicles: "Aplicar em todos os veículos do cliente",
    scope: "Abrangência",
    clientId: "Código do cliente",
    clientName: "Nome do cliente",
    vehicleId: "Código do veículo",
    vehiclePlate: "Veículos",
    appliesToAllUnits: "Aplicar em todas as unidades",
    unitIds: "Unidades",
    unitIdsHint: "Selecione as unidades quando a regra não valer para toda a rede.",
    fuelMinLiters: "Quantidade mínima de litros",
    benefitHours: "Quantidade de horas gratuitas",
    yardUnit: "Unidade",
    yardParkingSpots: "Vagas configuradas",
    yardOccupancyThreshold: "Gerar alerta com vagas preenchidas a partir de",
    yardStaleVehicleAmount: "Horas de permanência para alerta",
    yardStaleVehicleUnit: "Unidade de tempo",
    reason: "Justificativa",
    status: "Status",
    ruleTypePlaceholder: "Selecione o tipo de regra",
    targetPlaceholder: "Selecione o alvo",
    statusPlaceholder: "Selecione o status",
    scopePlaceholder: "Selecione a abrangência",
    clientPlaceholder: "Selecione o cliente",
    clientEmpty: "Nenhum cliente encontrado.",
    vehiclePlaceholder: "Selecione os veículos",
    vehicleEmpty: "Nenhum veículo encontrado para este cliente.",
    yardUnitPlaceholder: "Selecione a unidade",
    yardUnitEmpty: "Nenhuma unidade encontrada.",
    yardParkingSpotsEmpty: "Vagas não configuradas para esta unidade.",
    unitPlaceholder: "Selecione as unidades",
    unitEmpty: "Nenhuma unidade encontrada.",
    timeHours: "Horas",
    timeDays: "Dias",
    validation: {
      clientId: "Informe um código de cliente válido.",
      clientName: "Informe o nome do cliente.",
      vehicleId: "Informe um código de veículo válido.",
      vehiclePlate: "Informe a placa do veículo.",
      vehicleIds: "Selecione ao menos um veículo ou aplique em todos os veículos.",
      unitIds: "Selecione pelo menos uma unidade.",
      fuelMinLiters: "Informe uma quantidade mínima de litros maior que zero.",
      benefitHours: "Informe uma quantidade de horas de benefício maior que zero.",
      yardOccupancyThreshold: "Informe uma quantidade de vagas maior que zero.",
      yardStaleVehicleHours: "Informe um tempo sem saída maior que zero.",
      reason: "Informe uma justificativa com pelo menos 10 caracteres.",
    },
  },
  empty: {
    title: "Nenhuma regra cadastrada",
    description: "Cadastre uma regra para iniciar o controle comercial e operacional.",
  },
  filteredEmpty: {
    title: "Nenhuma regra encontrada",
    description: "Ajuste a busca ou os filtros aplicados.",
  },
  feedback: {
    loadError: "Não foi possível carregar as regras.",
    save: {
      loading: "Salvando regra...",
      success: "Regra salva.",
      error: "Não foi possível salvar a regra.",
    },
    toggle: {
      loading: "Atualizando regra...",
      success: "Regra atualizada.",
      error: "Não foi possível atualizar a regra.",
    },
  },
} as const
