export const myProfileCopy = {
  page: {
    title: "Meu perfil",
    subtitle: "Atualize dados de contato e foto da sua conta.",
  },
  empty: {
    title: "Perfil não disponível",
    description: "Não foi possível carregar os dados da sua conta.",
    action: "Recarregar",
  },
  error: {
    title: "Falha ao carregar perfil",
    action: "Tentar novamente",
    noticeTitle: "Não foi possível concluir a ação",
  },
  profile: {
    overviewTitle: "Resumo da conta",
    overviewDescription: "Identidade exibida no sistema e ações principais do perfil.",
    sectionTitle: "Informações da conta",
    sectionDescription: "Gerencie seus dados de perfil e revise informações protegidas.",
    avatarTitle: "Foto do perfil",
    avatarHint: "JPG, PNG ou WebP até 5 MB.",
    avatarAction: "Escolher foto",
    editTitle: "Dados editáveis",
    editDescription: "Nome, e-mail e telefone usados nas telas administrativas.",
    protectedTitle: "Dados protegidos",
    protectedDescription: "Informações controladas por políticas internas.",
    openEditModal: "Editar perfil",
    fields: {
      name: "Nome",
      email: "E-mail",
      phone: "Telefone",
      cpf: "CPF",
      role: "Perfil",
      unit: "Unidade",
      status: "Status",
    },
    fieldDescriptions: {
      name: "Nome exibido no sistema.",
      email: "Contato administrativo da conta.",
      phone: "Telefone para contato interno e recuperação.",
    },
    save: "Salvar alterações",
    saving: "Salvando...",
    noEmail: "Sem e-mail cadastrado",
    noPhone: "Sem telefone cadastrado",
    noCpf: "CPF protegido",
    noRole: "Sem perfil definido",
    globalUnit: "Escopo global",
    fallback: "—",
    statusLabels: {
      active: "Ativo",
      pending: "Pendente",
      inactive: "Inativo",
      password_reset: "Troca de senha",
      passkey_reset: "Reset de passkey",
    },
  },
  photoDialog: {
    title: "Foto do perfil",
    description: "Escolha ou arraste uma imagem para exibir na sua conta.",
    previewTitle: "Escolha uma imagem",
    dropTitle: "Solte a imagem aqui",
    dropDescription: "PNG, JPG ou WebP até 5 MB",
    replaceFile: "Trocar arquivo",
    cancel: "Cancelar",
    save: "Salvar",
    saving: "Salvando...",
    required: "Selecione uma imagem para continuar.",
  },
  feedback: {
    profile: {
      loading: "Salvando...",
      success: "Perfil atualizado.",
      error: "Não foi possível atualizar o perfil.",
    },
    changePassword: {
      loading: "Alterando...",
      success: "Senha alterada. Faça login novamente com a nova senha.",
      error: "Não foi possível alterar a senha. Verifique a senha atual.",
    },
  },
  changePassword: {
    title: "Alterar senha",
    description: "Informe a senha atual e defina uma nova senha de acesso.",
    currentLabel: "Senha atual",
    newLabel: "Nova senha",
    confirmLabel: "Confirme a nova senha",
    hint: "Mínimo 12 caracteres com maiúscula, minúscula, número e símbolo.",
    mismatch: "As senhas não coincidem.",
    sameAsCurrent: "A nova senha deve ser diferente da atual.",
    cancel: "Cancelar",
    save: "Alterar senha",
    saving: "Alterando...",
    action: "Alterar senha",
  },
} as const
