export const myProfileCopy = {
  page: {
    title: "Meu perfil",
    subtitle: "Atualize dados de contato e foto da sua conta.",
  },
  empty: {
    title: "Perfil não disponível",
    description: "Não foi possível carregar os dados da sua conta.",
    action: "Recarregar",
  },
  error: {
    title: "Falha ao carregar perfil",
    action: "Tentar novamente",
    noticeTitle: "Não foi possível concluir a ação",
  },
  profile: {
    sectionTitle: "Informações da conta",
    sectionDescription: "Gerencie seus dados de perfil e revise informações protegidas.",
    avatarTitle: "Foto do perfil",
    avatarHint: "JPG, PNG ou WebP até 5 MB.",
    avatarAction: "Alterar foto",
    editTitle: "Dados editáveis",
    editDescription: "Nome, e-mail e telefone usados nas telas administrativas.",
    protectedTitle: "Dados protegidos",
    protectedDescription: "Informações controladas por políticas internas.",
    openEditModal: "Editar perfil",
    fields: {
      name: "Nome",
      email: "E-mail",
      phone: "Telefone",
      cpf: "CPF",
      role: "Perfil",
      unit: "Unidade",
      status: "Status",
    },
    save: "Salvar alterações",
    saving: "Salvando...",
    noEmail: "Sem e-mail cadastrado",
    noPhone: "Sem telefone cadastrado",
    noCpf: "CPF protegido",
    noRole: "Sem perfil definido",
    globalUnit: "Escopo global",
    fallback: "—",
    statusLabels: {
      active: "Ativo",
      pending: "Pendente",
      inactive: "Inativo",
      password_reset: "Troca de senha",
      passkey_reset: "Reset de passkey",
    },
  },
  photoDialog: {
    title: "Alterar foto",
    description: "Envie uma imagem para atualizar a foto do perfil.",
    dropTitle: "Arraste e solte ou selecione",
    dropDescription: "PNG, JPG ou WebP até 5 MB",
    tabUpload: "Arquivo",
    tabUrl: "URL segura",
    imageUrl: "URL da imagem",
    imageUrlPlaceholder: "https://",
    imageUrlHint: "Use URL HTTPS com extensão JPG, PNG ou WebP.",
    cancel: "Cancelar",
    save: "Salvar",
    saving: "Salvando...",
    required: "Selecione uma imagem para continuar.",
    invalidUrl: "Informe uma URL HTTPS válida de imagem JPG, PNG ou WebP.",
  },
  feedback: {
    profile: {
      loading: "Salvando perfil...",
      success: "Perfil atualizado.",
      error: "Não foi possível atualizar o perfil.",
    },
  },
} as const
