export const pricesCopy = {
  page: {
    title: "Preços",
    subtitle: "Gerencie tabelas comerciais de estacionamento com vigência, escopo e valores.",
    searchPlaceholder: "Buscar tabelas de preço...",
  },
  actions: {
    activate: "Ativar",
    add: "Adicionar",
    edit: "Editar",
    deactivate: "Inativar",
    confirmActivate: "Ativar tabela",
    confirmDeactivate: "Inativar tabela",
    details: "Detalhes",
    clearFilters: "Limpar filtros",
    reload: "Recarregar",
    cancel: "Cancelar",
    save: "Salvar",
    saving: "Salvando...",
  },
  empty: {
    title: "Nenhuma tabela de preço encontrada",
    description: "Ainda não há registros cadastrados para exibição.",
  },
  filteredEmpty: {
    title: "Nenhum resultado encontrado",
    description: "Ajuste a busca ou os filtros para localizar registros.",
  },
  feedback: {
    loadError: "Não foi possível carregar as tabelas de preço.",
    saveSuccess: "Tabela de preço salva com sucesso.",
    saveError: "Não foi possível salvar. Revise os dados e tente novamente.",
    statusSuccess: "Status da tabela de preço atualizado.",
    statusError: "Não foi possível atualizar o status da tabela de preço.",
  },
  dialogs: {
    activateTitle: "Ativar tabela de preço",
    activateDescription:
      "Confirme para ativar esta tabela. Ela voltará a ficar disponível conforme a vigência configurada.",
    deactivateTitle: "Inativar tabela de preço",
    deactivateDescription:
      "Confirme para inativar esta tabela. A alteração pode ser revertida posteriormente.",
  },
  filters: {
    status: "Status",
    scope: "Escopo",
    unit: "Unidade",
  },
  table: {
    name: "Tabela",
    scope: "Escopo",
    unit: "Unidade",
    amount: "Valor base",
    cycleHours: "Ciclo",
    graceMinutes: "Carência",
    toleranceMinutes: "Tolerância",
    startsAt: "Início",
    endsAt: "Fim",
    status: "Status",
  },
  derived: {
    networkTableName: "Tabela da rede",
    unitTableName: "Tabela da unidade",
  },
  form: {
    createTitle: "Adicionar tabela de preço",
    editTitle: "Editar tabela de preço",
    description: "Defina escopo, valor, ciclo e período de vigência da tabela.",
    scope: "Escopo",
    unitId: "Código da unidade",
    unitName: "Unidade",
    amount: "Valor base",
    cycleHours: "Ciclo em horas",
    graceMinutes: "Carência em minutos",
    toleranceMinutes: "Tolerância em minutos",
    startsAt: "Início da vigência",
    endsAt: "Fim da vigência",
    status: "Status",
    notes: "Observações",
    optional: "Opcional",
    selectPlaceholder: "Selecione",
    help: {
      amount: "Valor cobrado no primeiro ciclo da permanência.",
      cycleHours: "Quantidade de horas que compõe cada ciclo de cobrança.",
      graceMinutes: "Período inicial em que nenhuma cobrança é aplicada.",
      toleranceMinutes:
        "Margem adicional após o ciclo antes de iniciar uma nova cobrança.",
    },
  },
  validation: {
    required: "Campo obrigatório.",
    positiveMoney: "Informe um valor base válido.",
    positiveInteger: "Informe um número inteiro maior que zero.",
    nonNegativeInteger: "Informe um número inteiro igual ou maior que zero.",
    invalidDate: "Informe uma data válida.",
    endBeforeStart: "A data final deve ser posterior à data inicial.",
  },
} as const
