export const rulesCopy = {
  page: {
    title: "Regras",
    subtitle: "Gerencie regras comerciais para clientes, veículos, unidades e condições operacionais.",
    searchPlaceholder: "Buscar por regra, cliente, veiculo ou observacao...",
  },
  actions: {
    activate: "Ativar",
    add: "Adicionar",
    edit: "Editar",
    deactivate: "Inativar",
    confirmActivate: "Ativar regra",
    confirmDeactivate: "Inativar regra",
    details: "Detalhes",
    cancel: "Cancelar",
    save: "Salvar",
    saving: "Salvando...",
  },
  empty: {
    title: "Nenhuma regra encontrada",
    description: "Ainda não há registros cadastrados para exibição.",
  },
  filteredEmpty: {
    title: "Nenhum resultado encontrado",
    description: "Ajuste a busca ou os filtros para localizar registros.",
  },
  feedback: {
    loadError: "Não foi possível carregar as regras.",
    saveSuccess: "Regra salva com sucesso.",
    saveError: "Não foi possível salvar. Revise os dados e tente novamente.",
    statusSuccess: "Status da regra atualizado.",
    statusError: "Não foi possível atualizar o status da regra.",
  },
  dialogs: {
    activateTitle: "Ativar regra",
    activateDescription:
      "Confirme para ativar esta regra. Ela voltará a ser aplicada nas condições configuradas.",
    deactivateTitle: "Inativar regra",
    deactivateDescription:
      "Confirme para inativar esta regra. A alteração pode ser revertida posteriormente.",
  },
  filters: {
    type: "Tipo",
    targetType: "Alvo",
    active: "Status",
  },
  table: {
    type: "Tipo",
    target: "Alvo",
    units: "Unidades",
    benefit: "Benefício",
    condition: "Condição",
    status: "Status",
    updatedAt: "Atualização",
  },
  form: {
    createTitle: "Adicionar regra",
    editTitle: "Editar regra",
    description: "Defina o alvo, a condição e o benefício da regra comercial.",
    type: "Tipo",
    targetType: "Alvo",
    clientId: "Código do cliente",
    clientName: "Nome do cliente",
    vehicleId: "Código do veículo",
    vehiclePlate: "Placa",
    appliesToAllUnits: "Aplicar em todas as unidades",
    unitIds: "Unidades",
    active: "Ativa",
    fuelMinLiters: "Litros mínimos",
    benefitHours: "Horas de benefício",
    yardOccupancyThreshold: "Ocupação mínima do pátio (%)",
    yardStaleVehicleHours: "Horas sem movimentação",
    notes: "Observações",
    selectPlaceholder: "Selecione",
  },
  validation: {
    required: "Campo obrigatório.",
    invalidClientId: "Informe um código de cliente válido.",
    positiveNumber: "Informe um número maior que zero.",
    percentage: "Informe percentual entre 1 e 100.",
  },
  labels: {
    active: "Ativa",
    inactive: "Inativa",
    allUnits: "Todas as unidades",
  },
} as const
