export const unitsCopy = {
  pages: {
    units: {
      title: "Unidades",
      subtitle: "Consulte as unidades sincronizadas do ERP.",
      searchPlaceholder: "Buscar unidades...",
    },
    unitUsers: {
      fallbackTitle: "Unidade não encontrada",
      fallbackDescription: "A unidade solicitada não existe ou ainda não foi sincronizada.",
      searchPlaceholder: "Buscar usuários...",
    },
  },
  actions: {
    backToUnits: "Voltar para unidades",
    configureYard: "Configurar pátio",
    history: "Histórico",
    sync: "Sincronizar",
    users: "Usuários",
  },
  sync: {
    historyLoadError: "Não foi possível carregar o histórico de sincronização.",
    runningTitle: "Sincronização em andamento",
    runningDescription: "A tela será liberada automaticamente ao finalizar.",
    feedback: {
      success: "Sincronização concluída.",
      error: "Não foi possível sincronizar as unidades.",
      inProgress: "Já existe uma sincronização de unidades em andamento.",
    },
  },
  filters: {
    brands: "Bandeiras",
    states: "Estados",
    roles: "Perfis",
    status: "Status",
  },
  table: {
    brand: "Bandeira",
    city: "Cidade",
    cityState: "Cidade/UF",
    cnpj: "CNPJ",
    companyCode: "Código",
    coordinates: "Coordenadas",
    email: "E-mail",
    erpSystem: "Sistema de gestão",
    erpSystemLabel: "ERP Monte Carlo",
    lastAccess: "Último acesso",
    legalName: "Razão social",
    managers: "Gerentes",
    networkIp: "IP da rede",
    noAccess: "Sem acesso",
    noEmail: "Sem e-mail",
    operators: "Operadores",
    passkey: "Passkey",
    phone: "Telefone",
    profile: "Perfil",
    spots: "Vagas",
    state: "UF",
    status: "Status",
    tradeName: "Unidade",
    users: "Usuários",
    yard: "Pátio",
  },
  details: {
    active: "Ativo",
    inactive: "Inativo",
    noMap: "Coordenadas indisponíveis",
  },
  yard: {
    dialogTitle: "Configurar pátio da unidade",
    statusLabel: "Status do pátio",
    spotsLabel: "Quantidade de vagas",
    statusActive: "Ativo",
    statusInactive: "Inativo",
    saveButton: "Salvar",
    cancelButton: "Cancelar",
    validationInvalidSpots: "Informe uma quantidade de vagas válida.",
    feedback: {
      loading: "Salvando configuração de pátio...",
      success: "Configuração de pátio atualizada.",
      error: "Não foi possível salvar a configuração de pátio.",
    },
  },
  empty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "As unidades ainda não foram sincronizadas do ERP.",
    unitUsersTitle: "Nenhum usuário vinculado",
    unitUsersDescription: "Esta unidade ainda não possui usuários operacionais vinculados.",
  },
  filteredEmpty: {
    unitsTitle: "Nenhuma unidade encontrada",
    unitsDescription: "Ajuste a busca ou os filtros para localizar uma unidade.",
    unitUsersTitle: "Nenhum usuário encontrado",
    unitUsersDescription: "Ajuste a busca ou os filtros para localizar usuários desta unidade.",
  },
  errors: {
    unitsLoad: "Não foi possível carregar as unidades.",
    unitUsersLoad: "Não foi possível carregar os usuários da unidade.",
    unitYardLoad: "Não foi possível carregar as configurações de pátio.",
    unitYardSave: "Não foi possível salvar a configuração de pátio.",
    unitYardInvalidUnit: "Unidade inválida para configuração de pátio.",
  },
} as const
