export const unitsCopy = {
  pages: {
    units: {
      title: "Unidades",
      subtitle: "Consulte as unidades cadastradas no sistema.",
      searchPlaceholder: "Buscar unidades...",
    },
    unitUsers: {
      fallbackTitle: "Unidade não encontrada",
      searchPlaceholder: "Buscar usuários...",
    },
  },
  actions: {
    history: "Histórico",
    sync: "Sincronizar",
    users: "Usuários",
    configureYard: "Configurar pátio",
  },
  filters: {
    brands: "Bandeiras",
    states: "Estados",
    roles: "Perfis",
    status: "Status",
  },
  table: {
    companyCode: "Código",
    legalName: "Razão social",
    tradeName: "Unidade",
    cnpj: "CNPJ",
    brand: "Bandeira",
    cityState: "Cidade/UF",
    coordinates: "Coordenadas",
    networkIp: "IP da rede",
    users: "Usuários",
    yard: "Pátio",
    spots: "Vagas",
    managers: "Gerentes",
    operators: "Operadores",
    profile: "Perfil",
    status: "Status",
    mfa: "MFA",
    lastAccess: "Último acesso",
    phone: "Telefone",
    email: "E-mail",
    noEmail: "Sem e-mail",
    noAccess: "Sem acesso",
    erpSystem: "Sistema de gestão",
    erpSystemLabel: "ERP Monte Carlo",
  },
  yard: {
    dialogTitle: "Configurar pátio da unidade",
    statusLabel: "Status do pátio",
    spotsLabel: "Quantidade de vagas",
    statusActive: "Ativo",
    statusInactive: "Inativo",
    saveButton: "Salvar",
    cancelButton: "Cancelar",
    validationInvalidSpots: "Informe uma quantidade de vagas válida (0 ou maior).",
    feedback: {
      loading: "Salvando configuração de pátio...",
      success: "Configuração de pátio atualizada.",
      error: "Não foi possível salvar a configuração de pátio.",
    },
  },
  errors: {
    unitsLoad: "Não foi possível carregar as unidades.",
    unitUsersLoad: "Não foi possível carregar os usuários da unidade.",
    unitYardLoad: "Não foi possível carregar as configurações de pátio.",
    unitYardSave: "Não foi possível salvar a configuração de pátio.",
    unitYardInvalidUnit: "Unidade inválida para configuração de pátio.",
  },
} as const
