export const usersCopy = {
  page: {
    title: "Usuários",
    subtitle: "Gerencie os usuários com acesso ao sistema.",
  },
  actions: {
    create: "Cadastrar",
    save: "Salvar",
    edit: "Editar",
    resetPassword: "Redefinir senha",
    resetPasskey: "Resetar passkey",
    clearLock: "Remover bloqueio",
    unblockUser: "Desbloquear usuário",
    revokeSessions: "Revogar sessões",
    blockUser: "Bloquear usuário",
  },
  dialogs: {
    createTitle: "Novo usuário",
    editTitle: "Editar usuário",
    createDescription: "Cadastre um novo usuário para acesso ao sistema.",
    editDescription: "Atualize os dados de acesso do usuário.",
    cancel: "Cancelar",
    blockTitle: "Bloquear usuário",
    blockDescription:
      "Tem certeza que deseja bloquear {{name}}? O acesso ao sistema será interrompido imediatamente.",
    blockDescriptionFallback: "Tem certeza que deseja bloquear este usuário?",
    blockConfirm: "Bloquear",
    resetTitle: "Redefinir senha",
    resetDescription:
      "Tem certeza que deseja redefinir a senha de {{name}}? Uma nova senha de primeiro acesso será exigida no próximo login.",
    resetDescriptionFallback: "Tem certeza que deseja redefinir a senha deste usuário?",
    resetConfirm: "Redefinir",
    resetPasskeyTitle: "Resetar passkey",
    resetPasskeyDescription:
      "Tem certeza que deseja resetar a passkey de {{name}}? O usuário deverá cadastrar uma nova no próximo acesso.",
    resetPasskeyDescriptionFallback: "Tem certeza que deseja resetar a passkey deste usuário?",
    resetPasskeyConfirm: "Resetar",
    clearLockTitle: "Remover bloqueio",
    clearLockDescription:
      "Tem certeza que deseja remover o bloqueio de {{name}}? O acesso será reativado imediatamente.",
    clearLockDescriptionFallback: "Tem certeza que deseja remover o bloqueio deste usuário?",
    clearLockConfirm: "Remover bloqueio",
    unblockTitle: "Desbloquear usuário",
    unblockDescription:
      "Tem certeza que deseja desbloquear {{name}}? O acesso ao sistema será reativado.",
    unblockDescriptionFallback: "Tem certeza que deseja desbloquear este usuário?",
    unblockConfirm: "Desbloquear",
    revokeSessionsTitle: "Revogar sessões",
    revokeSessionsDescription:
      "Tem certeza que deseja revogar todas as sessões ativas de {{name}}? O usuário será desconectado imediatamente.",
    revokeSessionsDescriptionFallback: "Tem certeza que deseja revogar as sessões deste usuário?",
    revokeSessionsConfirm: "Revogar",
  },
  filters: {
    role: "Perfis",
    status: "Status",
    unit: "Unidades",
    searchPlaceholder: "Buscar usuários...",
  },
  form: {
    requiredMark: "*",
    roleLabel: "Perfil",
    unitLabel: "Unidade",
    globalScopeHint: "Este perfil possui escopo global.",
    unitPlaceholder: "Buscar unidade...",
    globalUnitPlaceholder: "Global (todas as unidades)",
    unitEmpty: "Nenhuma unidade encontrada.",
    passwordLabel: "Senha de primeiro acesso",
    passwordDescription:
      "A senha de primeiro acesso é usada apenas no primeiro login. Após acessar, o usuário deverá criar uma nova senha.",
    fields: {
      name: "Nome",
      email: "E-mail",
      phone: "Telefone",
      cpf: "CPF",
    },
    placeholders: {
      name: "Digite o nome completo",
      email: "nome@empresa.com",
      phone: "(00) 00000-0000",
      role: "Selecione o perfil",
    },
  },
  details: {
    noEmail: "Sem e-mail",
    noAccess: "Sem acesso",
    globalUnit: "Global",
    passkeyActive: "Ativa",
    passkeyInactive: "Inativa",
  },
  feedback: {
    create: {
      loading: "Cadastrando usuário...",
      success: "Usuário cadastrado.",
      error: "Não foi possível salvar o usuário.",
    },
    update: {
      loading: "Atualizando usuário...",
      success: "Usuário atualizado.",
      error: "Não foi possível salvar o usuário.",
    },
    block: {
      loading: "Bloqueando usuário...",
      success: "Usuário bloqueado.",
      error: "Não foi possível bloquear o usuário.",
    },
    reset: {
      loading: "Redefinindo autenticação...",
      success: "Autenticação redefinida.",
      error: "Não foi possível redefinir a autenticação.",
    },
    resetPasskey: {
      loading: "Resetando passkey...",
      success: "Passkey resetada. O usuário deverá cadastrar uma nova.",
      error: "Não foi possível resetar a passkey.",
    },
    clearLock: {
      loading: "Removendo bloqueio...",
      success: "Bloqueio removido.",
      error: "Não foi possível remover o bloqueio.",
    },
    revokeSessions: {
      loading: "Revogando sessões...",
      success: "Sessões revogadas.",
      error: "Não foi possível revogar as sessões.",
    },
  },
  errors: {
    load: "Não foi possível carregar os usuários.",
    create: "Não foi possível criar o usuário.",
    update: "Não foi possível atualizar o usuário.",
    userNotFound: "Usuário não encontrado.",
    requiredUnit: "Selecione uma unidade para o perfil informado.",
    requiredFirstAccessPassword: "Informe a senha de primeiro acesso.",
    requiredCpf: "Informe o CPF do usuário.",
    requiredPhone: "Informe o telefone do usuário.",
    invalidPassword: "Senha inválida.",
  },
} as const
