export {
  AuthApiError,
  completeRequiredPassword,
  getCurrentAuthProfile,
  isPasskeySupported,
  registerAuthenticatedPasskey,
  requestAccessRecovery,
  signInWithPasskey,
  signInWithPassword,
  signOutCurrentSession,
  subscribeToAuthSessionChanges
} from "./api"
export {
  allRoles,
  appUserStatusLabels,
  authCapabilities,
  authCapabilityLabels,
  canManageRole,
  getAssignableRoles,
  hasAllPermissions,
  hasAnyPermission,
  isGlobalRole,
  isRoleSuperior,
  isUserRole,
  requiresSingleUnit,
  routeCapabilities, unitScopedRoles, unitScopedRoleValues, userRoleLabels,
  userRoleValues,
  type AppUserStatus,
  type AuthCapability,
  type UserRole
} from "./authorization"
export { AuthPageCard } from "./components"
export { authCopy } from "./constants"
export {
  AuthContext,
  AuthProvider,
  clearAuthInactivitySessionExpired,
  consumeAuthInactivitySessionExpired,
  createAuthAccessState,
  markAuthInactivitySessionExpired,
  readAuthInactivitySessionExpired,
  useAuth,
  useAuthInactivity,
  useAuthSession,
  type AuthAccessState,
  type AuthActions,
  type AuthContextValue,
  type AuthInactivityState,
  type AuthSessionStatus,
  type AuthSessionValue,
  type RequiredPasswordChallenge
} from "./context"
export {
  AUTH_FUNCTIONS,
  AUTH_INACTIVITY,
  AUTH_NEXT_ACTION,
  AUTH_PERMISSION,
  AUTH_PERMISSION_WILDCARD,
  AUTH_ROLE_KEY,
  AUTH_SESSION_TIMEOUTS,
  AUTH_STATUS,
  AUTH_STORAGE_KEYS,
  canAccessProtectedApp,
  isAuthPermission,
  isAuthStatus,
  normalizeAuthPermission,
  normalizeAuthPermissions,
  normalizeAuthStatus,
  requiresAccountRecovery,
  resolveAuthProfilePermissions,
  type AuthNextAction,
  type AuthPermission,
  type AuthRoleKey,
  type AuthStatus
} from "./contracts"
export type {
  AppUserProfile,
  AuthFlowActionResponse,
  AuthFlowStep,
  AuthPasskeyRegistrationResult,
  AuthPasswordNextAction,
  AuthPasswordResponse,
  AuthProfile,
  AuthRoleProfile,
  AuthSessionPayload,
  AuthStartResponse,
  ProfileActionResponse,
  RecoveryRequestResponse
} from "./types"
export {
  authCpfSchema,
  authLoginSchema,
  authPasswordSchema,
  authRecoverySchema,
  formatCpfInput,
  formatPhoneInput,
  getFirstIssueByPath,
  newPasswordSchema,
  normalizeCpf,
  normalizePhone,
  recoveryReasonValues,
  requiredPasswordSchema,
  type AuthLoginPayload,
  type AuthRecoveryFormValues,
  type AuthRecoveryPayload,
  type FieldErrors,
  type RecoveryReason,
  type RequiredPasswordValues
} from "./validation"
