export const permissionGroupLabels: Record<string, string> = {
  access_requests: "Solicitações de acesso",
  audit: "Auditoria",
  client_vehicles: "Veículos de clientes",
  clients: "Clientes",
  notifications: "Notificações",
  permissions: "Permissões",
  prices: "Preços",
  profile: "Perfil",
  rules: "Regras",
  settings: "Configurações",
  sync: "Sincronização",
  system: "Sistema",
  units: "Unidades",
  users: "Usuários",
}
