export const authCopy = {
  validation: {
    cpfRequired: "Informe o CPF.",
    cpfInvalid: "CPF inválido.",
    passwordRequired: "Informe a senha.",
    newPasswordRequired: "Informe a nova senha.",
    confirmPasswordRequired: "Confirme a nova senha.",
    passwordMin: "A senha deve ter pelo menos 8 caracteres.",
    newPasswordMin: "A nova senha deve ter pelo menos 12 caracteres.",
    newPasswordUppercase: "A nova senha deve conter uma letra maiúscula.",
    newPasswordLowercase: "A nova senha deve conter uma letra minúscula.",
    newPasswordNumber: "A nova senha deve conter um número.",
    newPasswordSymbol: "A nova senha deve conter um caractere especial.",
    confirmPasswordMismatch: "A confirmação deve ser igual à nova senha.",
    recoveryPhoneRequired: "Informe o telefone.",
    recoveryPhoneInvalid: "Informe um telefone válido.",
    recoveryEmailInvalid: "Informe um e-mail válido ou deixe o campo em branco.",
    recoveryReasonRequired: "Selecione o motivo da recuperação.",
    recoveryDescriptionMax: "A descrição deve ter no máximo 500 caracteres.",
  },
  errors: {
    unavailable: "Serviço indisponível no momento.",
    invalidCredentials: "Não foi possível autenticar com os dados informados.",
    sessionLoadFailed: "Não foi possível carregar a sessão atual.",
    logoutFailed: "Não foi possível revogar a sessão remota. A sessão local foi encerrada.",
    recoveryFailed: "Não foi possível registrar a solicitação de recuperação.",
    unsupportedNextAction: "Este fluxo de autenticação não está disponível nesta interface.",
    passkeyRequired:
      "Sua conta exige cadastro de passkey, mas este cliente ainda não possui um fluxo WebAuthn validado. Solicite liberação ou orientação a um administrador.",
  },
  login: {
    title: "Acesse sua conta",
    description: "Informe CPF e senha para continuar.",
    cpfLabel: "CPF",
    cpfPlaceholder: "000.000.000-00",
    passwordLabel: "Senha",
    passwordPlaceholder: "Informe sua senha",
    recoveryAction: "Recuperar acesso",
    submit: "Entrar",
    submitting: "Entrando...",
  },
  requiredPassword: {
    title: "Defina uma nova senha",
    description:
      "Sua conta exige troca de senha antes de continuar. Após concluir, informe a nova senha para acessar.",
    newPasswordLabel: "Nova senha",
    confirmPasswordLabel: "Confirmar nova senha",
    submit: "Salvar nova senha",
    submitting: "Salvando...",
    success: "Senha atualizada. Informe a nova senha para continuar.",
  },
  passkeyUnavailable: {
    title: "Cadastro de passkey necessário",
    description:
      "A senha foi validada, mas a conta exige cadastro de passkey. Por segurança, a sessão não foi aberta porque este cliente ainda não possui fluxo WebAuthn validado. Solicite suporte administrativo para concluir o acesso.",
    action: "Entendi",
  },
  recovery: {
    title: "Recuperar acesso",
    description: "Informe seus dados para solicitar recuperação de acesso.",
    cpfLabel: "CPF",
    phoneLabel: "Telefone",
    emailLabel: "E-mail",
    reasonLabel: "Motivo",
    reasonPlaceholder: "Selecione o motivo",
    descriptionLabel: "Detalhes",
    descriptionPlaceholder: "Inclua informações úteis para a análise administrativa.",
    submit: "Solicitar recuperação",
    submitting: "Enviando...",
    success: "Solicitação de recuperação registrada.",
    backToLogin: "Voltar para o login",
    reasons: {
      lostPhone: "Perdi acesso ao telefone",
      forgotPassword: "Esqueci minha senha",
      attemptsBlocked: "Bloqueio por tentativas",
      other: "Outro motivo",
    },
  },
  inactivity: {
    title: "Sessão prestes a expirar",
    secondsRemaining: (seconds: number) =>
      `Sua sessão será encerrada por inatividade em ${seconds} segundo${seconds === 1 ? "" : "s"}.`,
    continueSession: "Continuar sessão",
    signOutNow: "Sair agora",
    expiredTitle: "Sessão encerrada",
    expiredDescription:
      "Sua sessão foi encerrada por inatividade. Faça login novamente para continuar.",
    expiredAction: "Entendi",
  },
} as const
