export const auditCopy = {
  page: {
    title: "Auditoria",
    subtitle: "Acompanhe os eventos de segurança e as ações realizadas no sistema.",
    truncatedSubtitle: (limit: number) =>
      `Acompanhe os eventos de segurança e ações realizadas. Exibindo os ${limit} eventos mais recentes.`,
    searchPlaceholder: "Buscar na auditoria...",
  },
  feedback: {
    loadError: "Não foi possível carregar a trilha de auditoria.",
    exportLoading: "Gerando exportação de auditoria...",
    exportSuccess: "Exportação de auditoria concluída.",
    exportError: "Não foi possível exportar a auditoria.",
    exportEmptyError: "Não há eventos para exportar com os filtros atuais.",
  },
  actions: {
    details: "Detalhes",
    exportAll: "Exportar tudo",
    exportFiltered: "Exportar filtrados",
    clearFilters: "Limpar filtros",
  },
  filters: {
    responsible: "Responsável",
    events: "Eventos",
    scopes: "Escopos",
  },
  table: {
    occurredAt: "Data/hora",
    responsible: "Responsável",
    scope: "Escopo",
    event: "Evento",
    target: "Alvo",
    outcome: "Resultado",
    severity: "Severidade",
  },
  details: {
    reason: "Motivo",
    emptyValue: "—",
    fallbackDescription: "Sem informações adicionais.",
  },
  labels: {
    critical: "Crítico",
    failure: "Falha",
    no: "Não",
    success: "Sucesso",
    systemActor: "Sistema",
    yes: "Sim",
  },
  metadata: {
    labels: {
      actorRole: "Perfil do responsável",
      clientsCreated: "Clientes criados",
      clientsReceived: "Clientes recebidos",
      clientsUnchanged: "Clientes sem alteração",
      clientsUpdated: "Clientes atualizados",
      created: "Criados",
      decision: "Decisão",
      failed: "Falhas",
      locked: "Conta bloqueada",
      mode: "Modo",
      previousRole: "Perfil anterior",
      reason: "Motivo informado",
      received: "Recebidos",
      requestId: "Solicitação",
      role: "Perfil",
      status: "Status",
      targetRole: "Perfil alvo",
      trigger: "Gatilho",
      unchanged: "Sem alteração",
      updated: "Atualizados",
      vehiclesCreated: "Veículos criados",
      vehiclesReceived: "Veículos recebidos",
      vehiclesUnchanged: "Veículos sem alteração",
      vehiclesUpdated: "Veículos atualizados",
    },
    values: {
      admin: "Administrador",
      approved: "Aprovada",
      attempts_blocked: "Bloqueio por tentativas",
      auditor: "Auditor",
      automatic: "Automática",
      denied: "Negada",
      failed: "Falha",
      first_access: "Primeiro acesso",
      forgot_password: "Esqueci minha senha",
      full: "Completa",
      incremental: "Incremental",
      lost_phone: "Perdi ou troquei de celular",
      manual: "Manual",
      manager: "Gestor",
      operator: "Operador",
      other: "Outro motivo",
      owner: "Proprietário",
      passkey_reset: "Reset de passkey",
      password_reset: "Troca de senha",
      scheduled: "Agendada",
      success: "Sucesso",
      warning: "Atenção",
    },
  },
  technical: {
    valueLabels: {
      client_sync: "Sincronização de clientes",
      catch_handler: "Tratamento automático de falha",
      hubapi: "Hub API",
      sistema: "Sistema",
      unit_sync: "Sincronização de unidades",
      unknown: "Não identificado",
      usuario: "Usuário",
    },
    messages: {
      certificate:
        "Não foi possível conectar ao serviço externo por falha na validação do certificado.",
      externalService: "Não foi possível se comunicar com o serviço externo.",
    },
  },
} as const
