export const clientsCopy = {
  pages: {
    clients: {
      title: "Clientes",
      subtitle: "Consulte os clientes ativos sincronizados do ERP.",
      searchPlaceholder: "Buscar clientes...",
    },
    clientVehicles: {
      fallbackTitle: "Cliente não encontrado",
      fallbackDescription: "O cliente solicitado não existe ou ainda não foi sincronizado.",
      searchPlaceholder: "Buscar veículos...",
    },
  },
  actions: {
    backToClients: "Voltar",
    history: "Histórico",
    sync: "Sincronizar",
    openVehicles: "Veículos",
    toggleClientVip: "Cliente VIP",
    toggleVehicleVip: "Veículo VIP",
  },
  sync: {
    historyLoadError: "Não foi possível carregar o histórico de sincronização.",
    runningTitle: "Sincronização em andamento",
    runningDescription: "A tela será liberada automaticamente ao finalizar.",
    feedback: {
      success: "Sincronização concluída.",
      error: "Não foi possível sincronizar os clientes.",
      inProgress: "Já existe uma sincronização de clientes em andamento.",
    },
  },
  filters: {
    plates: "Placas",
    status: "Status",
    vip: "VIP",
  },
  table: {
    active: "Ativo",
    cityState: "Cidade/UF",
    client: "Cliente",
    code: "Código",
    customerCode: "Código do cliente",
    document: "CNPJ/CPF",
    driver: "Motorista",
    email: "E-mail",
    financialBlock: "Bloqueio financeiro",
    inactive: "Inativo",
    lastPurchase: "Data da última compra",
    legalName: "Nome/Razão social",
    phone: "Telefone",
    plate: "Placa",
    registrationDate: "Data de cadastro",
    status: "Status",
    tradeName: "Nome fantasia",
    vehicle: "Veículo",
    vehicleCode: "Código do veículo",
    vehicles: "Veículos",
    vip: "VIP",
    yes: "Sim",
    no: "Não",
  },
  empty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Os clientes ainda não foram sincronizados do ERP.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Este cliente ainda não possui veículos sincronizados.",
  },
  filteredEmpty: {
    clientsTitle: "Nenhum cliente encontrado",
    clientsDescription: "Ajuste a busca ou os filtros para localizar um cliente.",
    vehiclesTitle: "Nenhum veículo encontrado",
    vehiclesDescription: "Ajuste a busca ou os filtros para localizar um veículo.",
  },
  feedback: {
    clientVip: {
      loading: "Atualizando status VIP do cliente...",
      success: "Status VIP do cliente atualizado.",
      error: "Não foi possível atualizar o status VIP do cliente.",
    },
    vehicleVip: {
      loading: "Atualizando status VIP do veículo...",
      success: "Status VIP do veículo atualizado.",
      error: "Não foi possível atualizar o status VIP do veículo.",
    },
  },
  errors: {
    clientsLoad: "Não foi possível carregar os clientes.",
    vehiclesLoad: "Não foi possível carregar os veículos do cliente.",
  },
} as const
