export { ClientSyncBlockingDialog, ClientsSyncHistoryDialog } from "./components"
export {
  clientsCopy,
  clientsRoutePaths,
  CLIENT_VEHICLES_CACHE_KEY_PREFIX,
  CLIENT_VEHICLES_TABLE_COLUMN_VISIBILITY_KEY,
  CLIENTS_BATCH_SIZE,
  CLIENTS_CACHE_KEY,
  CLIENTS_MAX_BATCHES,
  CLIENTS_SYNC_HISTORY_CACHE_KEY,
  CLIENTS_SYNC_HISTORY_LIMIT,
  CLIENTS_TABLE_COLUMN_VISIBILITY_KEY,
  DEFAULT_CLIENTS_COLUMN_VISIBILITY,
  DEFAULT_CLIENT_VEHICLES_COLUMN_VISIBILITY,
} from "./constants"
export {
  useClient,
  useClientSyncHistory,
  useClientVipRules,
  useClientVehicles,
  useClientVehiclesTableFilters,
  useClients,
  useClientsTableFilters,
} from "./hooks"
export {
  getClientDetailItems,
  getClientVipStatus,
  getClientVehicleDetailItems,
  getVehicleVipStatus,
  mapClientToTableRow,
  mapClientVehicleToTableRow,
  normalizeDisplayName,
  parseClientRouteId,
  resolveClientStatus,
  resolveVipFlag,
  sanitizeErpClientPayload,
  sanitizeErpClientsPayload,
  sanitizeErpClientVehiclePayload,
  sanitizeErpClientVehiclesPayload,
  type Client,
  type ClientStatus,
  type ClientSyncCounters,
  type ClientSyncHistoryEntry,
  type ClientVipRuleRecord,
  type ClientVipRuleTargetType,
  type ClientSyncMode,
  type ClientsSnapshot,
  type ClientSyncStatus,
  type ClientSyncTrigger,
  type ClientTableRow,
  type ClientVehicle,
  type ClientVehicleTableRow,
  type ErpClientPayload,
  type ErpClientVehiclePayload,
  type TriggerClientsSyncResult,
  type VipFlag,
} from "./model"
export { ClientVehiclesRoute, ClientsRoute } from "./routes"
export {
  configureClientsGateway,
  getClientsGateway,
  isClientSyncInProgressError,
  listClientById,
  listClientVipRules,
  listClientVehiclesByClientId,
  listClients,
  listClientsSnapshot,
  listClientSyncHistory,
  listClientVehicles,
  resetClientsGateway,
  toggleClientVipRule,
  toggleVehicleVipRule,
  triggerClientsSync,
  type ClientsGateway,
} from "./services"
export {
  createClientsColumns,
  createClientVehiclesColumns,
} from "./table"
